version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OUTPUT_DIR=/app/deployment-package/output
    volumes:
      - ./deployment-package/output:/app/deployment-package/output
    restart: unless-stopped